# Generated by Django 4.2.7 on 2024-07-20 18:28

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_pedidoservicio_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[tienda.models.validar_nombre_producto]),
        ),
    ]
